sudo: required
services:
    - docker
before_install:
    - docker build -t niranjan/docker-react -f Dockerfile.dev .
script:
    - docker run niranjan/docker-react npm run test -- --coverage
deploy:
        edge: true
        provider: bluemixcloudfoundry
        username: niranjanbabu.mv@cognizant.com
        password: Kanipaka*143
        organization: CTS IPM
        space:  CTS IPM Cloud Development 
        manifest: manifest.yml          # (optional)  Defaults to manifest.yml.
        app_name: docker-react-new                # (optional)
        on:
          branch: master
