sudo: required
services:
    - docker
before_install:
    - docker build -t niranjan/docker-react -f Dockerfile.dev .
script:
    - docker run niranjan/docker-react npm run test -- --coverage
deploy:
        provider: bluemixcloudfoundry
        skip_cleanup: true
        manifest: manifest.yml
        username: $BLUEMIX_USER
        password: $BLUEMIX_PASSWORD
        organization: $BLUEMIX_ORGANIZATION
        space: $BLUEMIX_SPACE
        on:
          branch: master
