#Create OS
FROM node:alpine
#set working directory
WORKDIR '/app'

COPY package.json .
RUN npm install
COPY . .

#run the project
CMD ["npm","run","start"]

FROM nginx
  EXPOSE 80
  COPY --from=0 /app/build /usr/share/nginx/html
